eReolen/ereolengo

breol_base/breol_base.install
Related to https://github.com/eReolen/base/pull/43
=> ER-299: Enabled appbanners module

breol_base/breol_base.install, breol_base/breol_base.module, breol_base/js/breol_base_adgangsplatformen.js, ding_unilogin/ding_unilogin.admin.inc, ding_unilogin/ding_unilogin.module
See https://github.com/eReolen/base/pull/59
=> DDBTEAM-82: Fixed ad login

ding_unilogin/ding_unilogin.admin.inc, ding_unilogin/ding_unilogin.api.php, ding_unilogin/ding_unilogin.info, ding_unilogin/ding_unilogin.install, ding_unilogin/ding_unilogin.module, ding_unilogin/lib/DingUniloginUser.class.inc, ding_unilogin/lib/DingUniloginWSALicens.class.inc
https://jira.itkdev.dk/browse/ER-623
Adds whitelisting of institutions assigned to users signing in via UNI•Login.
=> ER_623: UNI•Login improvements

features/breol_frontend/plugins/content_types/cover_image.inc
https://jira.itkdev.dk/browse/ER-611
Hacking on a hack!
=> ER-611: Hacked check for node title

ding_unilogin/README.md, ding_unilogin/ding_unilogin.install, ding_unilogin/ding_unilogin.module, ding_unilogin/lib/DingUniloginWSIinst.class.inc, ding_unilogin/src/Controller/InstitutionController.php
https://jira.itkdev.dk/browse/ER-727
Adds information on municipalities to the UNI-Login API data.
=> ER-727: Unilogin municipalities

ding_unilogin/ding_unilogin.module
https://jira.itkdev.dk/browse/ER-733
=> ER-733: Fixed getting name from user

breol_base/breol_base.info, breol_base/breol_base.install
https://jira.itkdev.dk/browse/ER-524
Depends on https://github.com/eReolen/base/pull/71
=> ER-524: Menu item icons

breol_base/breol_base.module
https://jira.itkdev.dk/browse/ER-747
Depends on changes in https://github.com/eReolen/base/pull/73
=> ER-747: Series number

breol_base/breol_base.module
https://jira.itkdev.dk/browse/ER-772
=> ER-772: Added series to ting compact view

ding_unilogin/ding_unilogin.module, ding_unilogin/includes/ding_unilogin.admin.inc, ding_unilogin/src/Controller/InstitutionController.php
https://jira.itkdev.dk/browse/ER-759
=> ER-759: Added handling of institutions with (partly) missing municipality data

ding_unilogin/lib/DingUniloginUser.class.inc
https://jira.itkdev.dk/browse/ER-759
=> ER-759: Added missing fake municipality id during UNI•Login

ding_unilogin/lib/DingUniloginUser.class.inc
=> Revert "ER-759: Added missing fake municipality id during UNI•Login"

breol_app_warning/README.md, breol_app_warning/breol_app_warning.info, breol_app_warning/breol_app_warning.install, breol_app_warning/breol_app_warning.module, breol_app_warning/css/dialog.css, breol_app_warning/includes/breol_app_warning.admin.inc, breol_app_warning/js/dialog.js
https://jira.itkdev.dk/browse/ER-808
Adds a simple module for showing a warning when using the old app.
=> ER-808: Added app warning module

breol_app_warning/css/dialog.css
https://jira.itkdev.dk/browse/ER-808
=> ER-808: Adjusted title font size

breol_inspiration/breol_inspiration.features.field_instance.inc, features/breol_news/breol_news.info, features/breol_news/breol_news.module
https://jira.itkdev.dk/browse/ER-632
Related to https://github.com/eReolen/base/pull/106
=> ER-632: Allowed article_carousel in inspiration page

features/breol_frontend/plugins/content_types/search_result_count.inc
https://jira.itkdev.dk/browse/ER-981
Aligned display of search result count with ding2 profile.
=> ER-981: Fixed display of search result count

breol_news_page/breol_news_page.module
https://jira.itkdev.dk/browse/DEVSUPP-342
=> DEVSUPP-342: Used actual carousel title in display

features/breol_frontend/breol_frontend.pages_default.inc, features/breol_search_frontend/breol_search_frontend.pages_default.inc
https://jira.itkdev.dk/browse/ER-355
=> ER-355: Page titles

features/breol_news/breol_news.install
https://jira.itkdev.dk/browse/ER-1122
This reverts commit 15be68b5f9b7677ae2641141a63a97f6d67ef330.
=> Revert "ER-1122: Removed migration of news content"

media_videotool/includes/themes/media-videotool-video.tpl.php
https://jira.itkdev.dk/browse/ER-1099
=> ER-1099: Add allow="autoplay; fullscreen" attribute to VideoTool element

features/breol_video/breol_video.module
https://jira.itkdev.dk/browse/ER-1298
Handles no background color as a very light color, i.e. white.
=> ER-1298: Handled no background color

features/breol_video/breol_video.module
https://jira.itkdev.dk/browse/ER-1334
=> ER-1334: Display promoted materials based on search string

features/breol_search_frontend/breol_search_frontend.panels_default.inc
https://jira.itkdev.dk/browse/SUPP0RT-556
Depends on changes in https://github.com/eReolen/base/pull/268
Before:
After:
=> SUPP0RT-556: Hid sorting and page size controls

ding_unilogin/lib/DingUniloginWSIbruger.class.inc, ding_unilogin/lib/DingUniloginWSIinst.class.inc
https://jira.itkdev.dk/browse/ER-1379
Updates WSDL endpoints.
=> ER-1379: Updated WSDL endpoints

ding_unilogin/src/Controller/Api/InstitutionController.php
=> Revert "SUPP0RT-735: Allowed zero members of institution"

features/breol_video/breol_video.module
https://jira.itkdev.dk/browse/SUPP0RT-807
Updates video bundle search to show manifestations rather than works.
=> SUPP0RT-807: Video bundle search

ding_unilogin/ding_unilogin.module
https://jira.itkdev.dk/browse/ER-1447
When login in with uni-login from the front page redirect the user to "/user/me", trying to limit the front-page load for logged in users in the morning. 
N/A
N/A
=> ER-1447: Redirect unilogin to user page

ding_unilogin/lib/DingUniloginWSIinst.class.inc
https://jira.itkdev.dk/browse/ER-1454
Removes two unused functions.
=> ER-1454: Remove unused functions

features/breol_frontend/breol_frontend.features.inc
https://jira.itkdev.dk/browse/ER-1361
Image style that allow for square covers
n/a
If you have any further comments or questions for the reviewer please add them here.
=> ER-1361: Update carousel image style

paragraphs/breol_link_paragraph/breol_link_paragraph.module
https://jira.itkdev.dk/browse/ER-1480
Allow aimated gifs
Before:
After:
=> There ya go

paragraphs/breol_link_paragraph/breol_link_paragraph.features.field_instance.inc, paragraphs/breol_link_paragraph/breol_link_paragraph.module
https://jira.itkdev.dk/browse/ER-1497
Enables links target on link box links. Related to changes in https://github.com/eReolen/base/pull/326.
=> ER-1497: Link target on link box

features/breol_video/breol_video.features.field_base.inc, features/breol_video/breol_video.install, paragraphs/breol_carousel_paragraph/breol_carousel_paragraph.features.field_base.inc, paragraphs/breol_carousel_paragraph/breol_carousel_paragraph.install, paragraphs/breol_link_paragraph/breol_link_paragraph.features.field_base.inc, paragraphs/breol_link_paragraph/breol_link_paragraph.install
https://jira.itkdev.dk/browse/ER-1514
Change default colors in paragraph bundles
The new update hooks are an example of code duplication (actually triplication), but I, the programmer, can live with that.
=> ER-1514: Update paragraph bundle colors

features/breol_video/breol_video.features.field_base.inc, paragraphs/breol_carousel_paragraph/breol_carousel_paragraph.features.field_base.inc, paragraphs/breol_link_paragraph/breol_link_paragraph.features.field_base.inc
https://jira.itkdev.dk/browse/ER-1520
Add 4 light colors to paragraph bundles.
If you have any further comments or questions for the reviewer please add them here.
=> ER-1520: Add light colors

paragraphs/breol_link_paragraph/breol_link_paragraph.module
https://jira.itkdev.dk/browse/SUPP0RT-1333
Fixes handling of queries on links.
See related change in https://github.com/eReolen/base/pull/334.
=> SUPP0RT-1333: Fixed handling of links

ding_unilogin/includes/ding_unilogin.admin.inc, ding_unilogin/js/givadgang_bookmarklet.js
https://leantime.itkdev.dk/#/tickets/showTicket/1047
Renders a bookmarklet on `/admin/config/ding/unilogin_api#edit-ding-unilogin-admin-bookmarklet` to help eReolen GO export institutions from givadgang.dk to ereolengo.dk.
This is a hack! But it works!
=> Giv adgang bookmarklet
